export const userConstants = {
	REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
	REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
	REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

	LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
	LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
	LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
	
	LOGOUT: 'USER_LOGOUT',

	EDIT_PROFILE_REQUEST: 'USER_EDIT_REQUEST',
	EDIT_PROFILE_SUCCESS: 'USER_EDIT_SUCCESS',
	EDIT_PROFILE_FAILURE: 'USER_EDIT_FAILURE',
}